package io.github.orizynpx.arxwipe.domain.model

import io.github.orizynpx.arxwipe.R

object ArxivTaxonomy {
    val categories: List<PaperCategory> = listOf(
        
        PaperCategory("cs.*", R.string.cat_cs_all_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_all_desc),
        PaperCategory("cs.AI", R.string.cat_cs_ai_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_ai_desc),
        PaperCategory("cs.AR", R.string.cat_cs_ar_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_ar_desc),
        PaperCategory("cs.CC", R.string.cat_cs_cc_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_cc_desc),
        PaperCategory("cs.CE", R.string.cat_cs_ce_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_ce_desc),
        PaperCategory("cs.CG", R.string.cat_cs_cg_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_cg_desc),
        PaperCategory("cs.CL", R.string.cat_cs_cl_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_cl_desc),
        PaperCategory("cs.CR", R.string.cat_cs_cr_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_cr_desc),
        PaperCategory("cs.CV", R.string.cat_cs_cv_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_cv_desc),
        PaperCategory("cs.CY", R.string.cat_cs_cy_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_cy_desc),
        PaperCategory("cs.DB", R.string.cat_cs_db_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_db_desc),
        PaperCategory("cs.DC", R.string.cat_cs_dc_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_dc_desc),
        PaperCategory("cs.DL", R.string.cat_cs_dl_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_dl_desc),
        PaperCategory("cs.DM", R.string.cat_cs_dm_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_dm_desc),
        PaperCategory("cs.DS", R.string.cat_cs_ds_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_ds_desc),
        PaperCategory("cs.ET", R.string.cat_cs_et_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_et_desc),
        PaperCategory("cs.FL", R.string.cat_cs_fl_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_fl_desc),
        PaperCategory("cs.GL", R.string.cat_cs_gl_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_gl_desc),
        PaperCategory("cs.GR", R.string.cat_cs_gr_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_gr_desc),
        PaperCategory("cs.GT", R.string.cat_cs_gt_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_gt_desc),
        PaperCategory("cs.HC", R.string.cat_cs_hc_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_hc_desc),
        PaperCategory("cs.IR", R.string.cat_cs_ir_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_ir_desc),
        PaperCategory("cs.IT", R.string.cat_cs_it_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_it_desc),
        PaperCategory("cs.LG", R.string.cat_cs_lg_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_lg_desc),
        PaperCategory("cs.LO", R.string.cat_cs_lo_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_lo_desc),
        PaperCategory("cs.MA", R.string.cat_cs_ma_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_ma_desc),
        PaperCategory("cs.MM", R.string.cat_cs_mm_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_mm_desc),
        PaperCategory("cs.MS", R.string.cat_cs_ms_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_ms_desc),
        PaperCategory("cs.NE", R.string.cat_cs_ne_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_ne_desc),
        PaperCategory("cs.NI", R.string.cat_cs_ni_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_ni_desc),
        PaperCategory("cs.OH", R.string.cat_cs_oh_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_oh_desc),
        PaperCategory("cs.OS", R.string.cat_cs_os_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_os_desc),
        PaperCategory("cs.PF", R.string.cat_cs_pf_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_pf_desc),
        PaperCategory("cs.PL", R.string.cat_cs_pl_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_pl_desc),
        PaperCategory("cs.RO", R.string.cat_cs_ro_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_ro_desc),
        PaperCategory("cs.SC", R.string.cat_cs_sc_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_sc_desc),
        PaperCategory("cs.SD", R.string.cat_cs_sd_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_sd_desc),
        PaperCategory("cs.SE", R.string.cat_cs_se_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_se_desc),
        PaperCategory("cs.SI", R.string.cat_cs_si_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_si_desc),
        PaperCategory("cs.SY", R.string.cat_cs_sy_name, MainField.COMPUTER_SCIENCE, R.string.cat_cs_sy_desc),

        
        PaperCategory("econ.*", R.string.cat_econ_all_name, MainField.ECONOMICS, R.string.cat_econ_all_desc),
        PaperCategory("econ.EM", R.string.cat_econ_em_name, MainField.ECONOMICS, R.string.cat_econ_em_desc),
        PaperCategory("econ.GN", R.string.cat_econ_gn_name, MainField.ECONOMICS, R.string.cat_econ_gn_desc),
        PaperCategory("econ.TH", R.string.cat_econ_th_name, MainField.ECONOMICS, R.string.cat_econ_th_desc),

        
        PaperCategory("eess.*", R.string.cat_eess_all_name, MainField.ELECTRICAL_ENGINEERING, R.string.cat_eess_all_desc),
        PaperCategory("eess.AS", R.string.cat_eess_as_name, MainField.ELECTRICAL_ENGINEERING, R.string.cat_eess_as_desc),
        PaperCategory("eess.IV", R.string.cat_eess_iv_name, MainField.ELECTRICAL_ENGINEERING, R.string.cat_eess_iv_desc),
        PaperCategory("eess.SP", R.string.cat_eess_sp_name, MainField.ELECTRICAL_ENGINEERING, R.string.cat_eess_sp_desc),
        PaperCategory("eess.SY", R.string.cat_eess_sy_name, MainField.ELECTRICAL_ENGINEERING, R.string.cat_eess_sy_desc),

        
        PaperCategory("math.*", R.string.cat_math_all_name, MainField.MATHEMATICS, R.string.cat_math_all_desc),
        PaperCategory("math.AC", R.string.cat_math_ac_name, MainField.MATHEMATICS, R.string.cat_math_ac_desc),
        PaperCategory("math.AG", R.string.cat_math_ag_name, MainField.MATHEMATICS, R.string.cat_math_ag_desc),
        PaperCategory("math.AP", R.string.cat_math_ap_name, MainField.MATHEMATICS, R.string.cat_math_ap_desc),
        PaperCategory("math.AT", R.string.cat_math_at_name, MainField.MATHEMATICS, R.string.cat_math_at_desc),
        PaperCategory("math.CA", R.string.cat_math_ca_name, MainField.MATHEMATICS, R.string.cat_math_ca_desc),
        PaperCategory("math.CO", R.string.cat_math_co_name, MainField.MATHEMATICS, R.string.cat_math_co_desc),
        PaperCategory("math.CT", R.string.cat_math_ct_name, MainField.MATHEMATICS, R.string.cat_math_ct_desc),
        PaperCategory("math.CV", R.string.cat_math_cv_name, MainField.MATHEMATICS, R.string.cat_math_cv_desc),
        PaperCategory("math.DG", R.string.cat_math_dg_name, MainField.MATHEMATICS, R.string.cat_math_dg_desc),
        PaperCategory("math.DS", R.string.cat_math_ds_name, MainField.MATHEMATICS, R.string.cat_math_ds_desc),
        PaperCategory("math.FA", R.string.cat_math_fa_name, MainField.MATHEMATICS, R.string.cat_math_fa_desc),
        PaperCategory("math.GM", R.string.cat_math_gm_name, MainField.MATHEMATICS, R.string.cat_math_gm_desc),
        PaperCategory("math.GN", R.string.cat_math_gn_name, MainField.MATHEMATICS, R.string.cat_math_gn_desc),
        PaperCategory("math.GR", R.string.cat_math_gr_name, MainField.MATHEMATICS, R.string.cat_math_gr_desc),
        PaperCategory("math.GT", R.string.cat_math_gt_name, MainField.MATHEMATICS, R.string.cat_math_gt_desc),
        PaperCategory("math.HO", R.string.cat_math_ho_name, MainField.MATHEMATICS, R.string.cat_math_ho_desc),
        PaperCategory("math.IT", R.string.cat_math_it_name, MainField.MATHEMATICS, R.string.cat_math_it_desc),
        PaperCategory("math.KT", R.string.cat_math_kt_name, MainField.MATHEMATICS, R.string.cat_math_kt_desc),
        PaperCategory("math.LO", R.string.cat_math_lo_name, MainField.MATHEMATICS, R.string.cat_math_lo_desc),
        PaperCategory("math.MG", R.string.cat_math_mg_name, MainField.MATHEMATICS, R.string.cat_math_mg_desc),
        PaperCategory("math.MP", R.string.cat_math_mp_name, MainField.MATHEMATICS, R.string.cat_math_mp_desc),
        PaperCategory("math.NA", R.string.cat_math_na_name, MainField.MATHEMATICS, R.string.cat_math_na_desc),
        PaperCategory("math.NT", R.string.cat_math_nt_name, MainField.MATHEMATICS, R.string.cat_math_nt_desc),
        PaperCategory("math.OA", R.string.cat_math_oa_name, MainField.MATHEMATICS, R.string.cat_math_oa_desc),
        PaperCategory("math.OC", R.string.cat_math_oc_name, MainField.MATHEMATICS, R.string.cat_math_oc_desc),
        PaperCategory("math.PR", R.string.cat_math_pr_name, MainField.MATHEMATICS, R.string.cat_math_pr_desc),
        PaperCategory("math.QA", R.string.cat_math_qa_name, MainField.MATHEMATICS, R.string.cat_math_qa_desc),
        PaperCategory("math.RA", R.string.cat_math_ra_name, MainField.MATHEMATICS, R.string.cat_math_ra_desc),
        PaperCategory("math.RT", R.string.cat_math_rt_name, MainField.MATHEMATICS, R.string.cat_math_rt_desc),
        PaperCategory("math.SG", R.string.cat_math_sg_name, MainField.MATHEMATICS, R.string.cat_math_sg_desc),
        PaperCategory("math.SP", R.string.cat_math_sp_name, MainField.MATHEMATICS, R.string.cat_math_sp_desc),
        PaperCategory("math.ST", R.string.cat_math_st_name, MainField.MATHEMATICS, R.string.cat_math_st_desc),

        
        PaperCategory("physics.*", R.string.cat_physics_all_name, MainField.PHYSICS, R.string.cat_physics_all_desc),
        PaperCategory("astro-ph.*", R.string.cat_astro_ph_all_name, MainField.PHYSICS, R.string.cat_astro_ph_all_desc),
        PaperCategory("cond-mat.*", R.string.cat_cond_mat_all_name, MainField.PHYSICS, R.string.cat_cond_mat_all_desc),
        PaperCategory("gr-qc", R.string.cat_gr_qc_name, MainField.PHYSICS, R.string.cat_gr_qc_desc),
        PaperCategory("hep-ex", R.string.cat_hep_ex_name, MainField.PHYSICS, R.string.cat_hep_ex_desc),
        PaperCategory("hep-lat", R.string.cat_hep_lat_name, MainField.PHYSICS, R.string.cat_hep_lat_desc),
        PaperCategory("hep-ph", R.string.cat_hep_ph_name, MainField.PHYSICS, R.string.cat_hep_ph_desc),
        PaperCategory("hep-th", R.string.cat_hep_th_name, MainField.PHYSICS, R.string.cat_hep_th_desc),
        PaperCategory("math-ph", R.string.cat_math_ph_name, MainField.PHYSICS, R.string.cat_math_ph_desc),
        PaperCategory("nlin.*", R.string.cat_nlin_all_name, MainField.PHYSICS, R.string.cat_nlin_all_desc),
        PaperCategory("nucl-ex", R.string.cat_nucl_ex_name, MainField.PHYSICS, R.string.cat_nucl_ex_desc),
        PaperCategory("nucl-th", R.string.cat_nucl_th_name, MainField.PHYSICS, R.string.cat_nucl_th_desc),
        PaperCategory("quant-ph", R.string.cat_quant_ph_name, MainField.PHYSICS, R.string.cat_quant_ph_desc),
        PaperCategory("physics.acc-ph", R.string.cat_physics_acc_ph_name, MainField.PHYSICS, R.string.cat_physics_acc_ph_desc),
        PaperCategory("physics.ao-ph", R.string.cat_physics_ao_ph_name, MainField.PHYSICS, R.string.cat_physics_ao_ph_desc),
        PaperCategory("physics.app-ph", R.string.cat_physics_app_ph_name, MainField.PHYSICS, R.string.cat_physics_app_ph_desc),
        PaperCategory("physics.bio-ph", R.string.cat_physics_bio_ph_name, MainField.PHYSICS, R.string.cat_physics_bio_ph_desc),
        PaperCategory("physics.chem-ph", R.string.cat_physics_chem_ph_name, MainField.PHYSICS, R.string.cat_physics_chem_ph_desc),
        PaperCategory("physics.class-ph", R.string.cat_physics_class_ph_name, MainField.PHYSICS, R.string.cat_physics_class_ph_desc),
        PaperCategory("physics.comp-ph", R.string.cat_physics_comp_ph_name, MainField.PHYSICS, R.string.cat_physics_comp_ph_desc),
        PaperCategory("physics.data-an", R.string.cat_physics_data_an_name, MainField.PHYSICS, R.string.cat_physics_data_an_desc),
        PaperCategory("physics.ed-ph", R.string.cat_physics_ed_ph_name, MainField.PHYSICS, R.string.cat_physics_ed_ph_desc),
        PaperCategory("physics.flu-dyn", R.string.cat_physics_flu_dyn_name, MainField.PHYSICS, R.string.cat_physics_flu_dyn_desc),
        PaperCategory("physics.geo-ph", R.string.cat_physics_geo_ph_name, MainField.PHYSICS, R.string.cat_physics_geo_ph_desc),
        PaperCategory("physics.hist-ph", R.string.cat_physics_hist_ph_name, MainField.PHYSICS, R.string.cat_physics_hist_ph_desc),
        PaperCategory("physics.ins-det", R.string.cat_physics_ins_det_name, MainField.PHYSICS, R.string.cat_physics_ins_det_desc),
        PaperCategory("physics.med-ph", R.string.cat_physics_med_ph_name, MainField.PHYSICS, R.string.cat_physics_med_ph_desc),
        PaperCategory("physics.optics", R.string.cat_physics_optics_name, MainField.PHYSICS, R.string.cat_physics_optics_desc),
        PaperCategory("physics.plasm-ph", R.string.cat_physics_plasm_ph_name, MainField.PHYSICS, R.string.cat_physics_plasm_ph_desc),
        PaperCategory("physics.pop-ph", R.string.cat_physics_pop_ph_name, MainField.PHYSICS, R.string.cat_physics_pop_ph_desc),
        PaperCategory("physics.soc-ph", R.string.cat_physics_soc_ph_name, MainField.PHYSICS, R.string.cat_physics_soc_ph_desc),
        PaperCategory("physics.space-ph", R.string.cat_physics_space_ph_name, MainField.PHYSICS, R.string.cat_physics_space_ph_desc),

        
        PaperCategory("q-bio.*", R.string.cat_q_bio_all_name, MainField.QUANTITATIVE_BIOLOGY, R.string.cat_q_bio_all_desc),
        PaperCategory("q-bio.BM", R.string.cat_q_bio_bm_name, MainField.QUANTITATIVE_BIOLOGY, R.string.cat_q_bio_bm_desc),
        PaperCategory("q-bio.CB", R.string.cat_q_bio_cb_name, MainField.QUANTITATIVE_BIOLOGY, R.string.cat_q_bio_cb_desc),
        PaperCategory("q-bio.GN", R.string.cat_q_bio_gn_name, MainField.QUANTITATIVE_BIOLOGY, R.string.cat_q_bio_gn_desc),
        PaperCategory("q-bio.MN", R.string.cat_q_bio_mn_name, MainField.QUANTITATIVE_BIOLOGY, R.string.cat_q_bio_mn_desc),
        PaperCategory("q-bio.NC", R.string.cat_q_bio_nc_name, MainField.QUANTITATIVE_BIOLOGY, R.string.cat_q_bio_nc_desc),
        PaperCategory("q-bio.PE", R.string.cat_q_bio_pe_name, MainField.QUANTITATIVE_BIOLOGY, R.string.cat_q_bio_pe_desc),
        PaperCategory("q-bio.QM", R.string.cat_q_bio_qm_name, MainField.QUANTITATIVE_BIOLOGY, R.string.cat_q_bio_qm_desc),
        PaperCategory("q-bio.SC", R.string.cat_q_bio_sc_name, MainField.QUANTITATIVE_BIOLOGY, R.string.cat_q_bio_sc_desc),
        PaperCategory("q-bio.TO", R.string.cat_q_bio_to_name, MainField.QUANTITATIVE_BIOLOGY, R.string.cat_q_bio_to_desc),

        
        PaperCategory("q-fin.*", R.string.cat_q_fin_all_name, MainField.QUANTITATIVE_FINANCE, R.string.cat_q_fin_all_desc),
        PaperCategory("q-fin.CP", R.string.cat_q_fin_cp_name, MainField.QUANTITATIVE_FINANCE, R.string.cat_q_fin_cp_desc),
        PaperCategory("q-fin.EC", R.string.cat_q_fin_ec_name, MainField.QUANTITATIVE_FINANCE, R.string.cat_q_fin_ec_desc),
        PaperCategory("q-fin.GN", R.string.cat_q_fin_gn_name, MainField.QUANTITATIVE_FINANCE, R.string.cat_q_fin_gn_desc),
        PaperCategory("q-fin.MF", R.string.cat_q_fin_mf_name, MainField.QUANTITATIVE_FINANCE, R.string.cat_q_fin_mf_desc),
        PaperCategory("q-fin.PM", R.string.cat_q_fin_pm_name, MainField.QUANTITATIVE_FINANCE, R.string.cat_q_fin_pm_desc),
        PaperCategory("q-fin.PR", R.string.cat_q_fin_pr_name, MainField.QUANTITATIVE_FINANCE, R.string.cat_q_fin_pr_desc),
        PaperCategory("q-fin.RM", R.string.cat_q_fin_rm_name, MainField.QUANTITATIVE_FINANCE, R.string.cat_q_fin_rm_desc),
        PaperCategory("q-fin.ST", R.string.cat_q_fin_st_name, MainField.QUANTITATIVE_FINANCE, R.string.cat_q_fin_st_desc),
        PaperCategory("q-fin.TR", R.string.cat_q_fin_tr_name, MainField.QUANTITATIVE_FINANCE, R.string.cat_q_fin_tr_desc),

        
        PaperCategory("stat.*", R.string.cat_stat_all_name, MainField.STATISTICS, R.string.cat_stat_all_desc),
        PaperCategory("stat.AP", R.string.cat_stat_ap_name, MainField.STATISTICS, R.string.cat_stat_ap_desc),
        PaperCategory("stat.CO", R.string.cat_stat_co_name, MainField.STATISTICS, R.string.cat_stat_co_desc),
        PaperCategory("stat.ME", R.string.cat_stat_me_name, MainField.STATISTICS, R.string.cat_stat_me_desc),
        PaperCategory("stat.ML", R.string.cat_stat_ml_name, MainField.STATISTICS, R.string.cat_stat_ml_desc),
        PaperCategory("stat.TH", R.string.cat_stat_th_name, MainField.STATISTICS, R.string.cat_stat_th_desc)
    )

    fun getByCategoryGroup(group: MainField): List<PaperCategory> {
        return categories.filter { it.group == group }
    }
}
